### ISSUE TITLE
NotificationTapped doesn't work with splash screen.

### ISSUE THREAD

**Issue by koosha72** [thudugala/Plugin.LocalNotification#50]
**Describe the bug**
When I use a splash activity tap event never fires.

**To Reproduce**
1. Create a SplashActivity class.
2. Set its MainLauncher to true.
3. Start MainActivity inside its OnCreate method.
4. Create a notification
5. Tap on the notification

**Expected behavior**
NotificationTapped event gets fired

**Platform (please complete the following information):**
-OS: Android 9 

**Smartphone (please complete the following information):**
 - Device: genymotion emulator
 - OS: Android
 - Version 23

**Comment by thudugala** [comment]
Please attach a sample project.

**Comment by jslachta** [comment]
I think this is not a bug. Since Xamarin.Forms does not support splashscreen itself, adding new Splashscreen Activity often "breaks" the component initialization at startup. It should be enough to mimic the behavior and pass the original data we want from the splashscreen Activity.

In order to make the NotificationTapped event working, you must pass the data from the original Intent (SplashScreen Activity) to your Main Activity intent.

```
            string data = Intent.GetStringExtra(ExtraReturnDataAndroid);
            Intent intent = new Intent(Application.Context, typeof(MainActivity));
            intent.PutExtra(ExtraReturnDataAndroid, data);

            StartActivity(intent);
```

**Comment by thudugala** [comment]
@koosha72  Is there possibility to attach a sample project here, so that I can understand the issue in more detail ?

**Comment by thomasgalliker** [comment]
What is 'ExtraReturnDataAndroid' in your sample code above?

**Comment by thomasgalliker** [comment]
@thudugala this is the SplashActivity I'm using to handover the ExtraReturnDataAndroid payload. It works well, but it's a bit nasty to declare my own ExtraReturnDataAndroid variable.

```
    [Activity(Theme = "@style/SplashTheme",
        NoHistory = true ,
        MainLauncher = true)]
    public class SplashActivity : Activity
    {
        private static readonly string ExtraReturnDataAndroid = "Plugin.LocalNotification.RETURN_DATA";

        protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);

            InvokeMainActivity();
        }

        private void InvokeMainActivity()
        {
            var data = Intent.GetStringExtra(ExtraReturnDataAndroid);
            Intent intent = new Intent(Application.Context, typeof(MainActivity));

            if (!string.IsNullOrWhiteSpace(data))
            {
                intent.PutExtra(ExtraReturnDataAndroid, data);
            }

            StartActivity(intent);
        }

    }

```

**Comment by thudugala** [comment]
@thomasgalliker will make it public in next version. You can also send me a PR.

**Comment by thudugala** [comment]
@thomasgalliker Fixed in v4.1.4

**Comment by thomasgalliker** [comment]
Cool thanks for this quick response.

**Comment by gayugokhale** [comment]
I am using version 5.2.0 but issue is still there. I am not seeing any `ExtraReturnDataAndroid ` variable. and I tried to add that code in my splash activity but issue still persists. NotificationTapped event not fired when I tap on notification. It navigates to login screen in my case.
